# Generated by Django 4.1.5 on 2023-01-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_tasks_hardness'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shop_sizes',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X large')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='hardness',
            field=models.FloatField(default=1.0),
        ),
    ]
