# Generated by Django 4.1.5 on 2023-01-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_shop_sizes_alter_tasks_hardness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='hardness',
            field=models.FloatField(default=1.0, verbose_name='Уровень сложности'),
        ),
    ]
