# Generated by Django 4.1.7 on 2023-03-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_news_shop_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название статьи'),
        ),
    ]
